#!/bin/bash
# EAI pick_place G1-D Motus training (4 GPU: 0,1,2,3)
# Subtask + Progress detection enabled (mot_decoder mode, 4-layer decoder)
# Data: 3 datasets combined (264 episodes, 4 subtasks each)
#   - pick_place_100_motus   (100 episodes)
#   - pick_place_9_16_motus  (117 episodes)
#   - pick_place_916_motus   (47 episodes)
# Pretrain: checkpoints/88
# phase_info generated by: tmp/generate_phase_info.py from data/subtask.json

set -e

source /root/miniconda3/etc/profile.d/conda.sh
conda activate motus

export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

echo "============== EAI pick_place G1-D ALL Motus Training (Subtask+Progress, 4 GPU) =============="
echo "Python: $(which python)"
echo "GPU: 0,1,2,3"
echo "Data: data/all/ (pick_place_100_motus + pick_place_9_16_motus + pick_place_916_motus, 264 episodes)"
echo "Subtask: mot_decoder, 4-layer, subtask_supervision_ratio=1.0"
echo "Progress: regression head, normalized phase position"
echo "Pretrain: /home/ma-user/work/wx1513998/checkpoints/88"

cd /home/ma-user/work/wx1513998/motus_guass_best_2

mkdir -p /home/ma-user/work/wx1513998/motus_eai_pick_place_all_subtask/checkpoints
mkdir -p /home/ma-user/work/wx1513998/motus_eai_pick_place_all_subtask/tensorboard

export OMP_NUM_THREADS=2
export NCCL_TIMEOUT=1800
export NCCL_SOCKET_IFNAME=lo
export TOKENIZERS_PARALLELISM=false

CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun \
    --nnodes=1 \
    --nproc_per_node=4 \
    --node_rank=0 \
    --master_addr=127.0.0.1 \
    --master_port=29102 \
    train/train_wan_vlm_mask_reweight_progress.py \
    --deepspeed configs/zero1.json \
    --config /home/ma-user/work/wx1513998/tmp/eai_pick_place_g1d_all_subtask.yaml \
    --report_to tensorboard \
    2>&1 | tee /home/ma-user/work/wx1513998/motus_eai_pick_place_all_subtask_train.log

EXIT_CODE=${PIPESTATUS[0]}
echo "Training exit code: $EXIT_CODE"
echo "============== Training End =============="
exit $EXIT_CODE
